# Generated by Django 5.0.2 on 2024-02-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_member_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='full_name',
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
    ]
