# Generated by Django 5.0.2 on 2024-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_member_full_name_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
