# Generated by Django 5.0.2 on 2024-02-22 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_member_device_token_alter_member_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
    ]
