# Generated by Django 5.0.2 on 2024-02-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_workspace_invite_code'),
    ]

    operations = [
    ]
