# Generated by Django 5.0.2 on 2024-02-22 10:33

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_workspace_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='invite_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, verbose_name='Invite Code'),
        ),
    ]
